# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daily Life of a Developer
email: mrezamaghool@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The daily life of Mohammad Reza Maghoul, an Iranian Software Developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ivir3zam
github_username:  ivir3zam

# Build settings
markdown: kramdown
